/** Content pools for the demo dataset. Everything here is fictional; company names and people are invented. */

export interface Family {
  key: string;
  titles: string[];
  skills: string[];
  /** Typical annual base salary for ~2 years of experience, in lakh INR. */
  lpa: number;
  teams: string[];
  /** Responsibility bullets; {a} {b} {c} are replaced with the job's first three skills. */
  duties: string[];
}

export const FAMILIES: Family[] = [
  {
    key: 'backend',
    titles: ['Backend Engineer', 'API Developer', 'Software Engineer', 'Platform Engineer', 'Full Stack Developer'],
    skills: [
      'Node.js',
      'Express',
      'MongoDB',
      'PostgreSQL',
      'Redis',
      'Docker',
      'AWS',
      'REST APIs',
      'TypeScript',
      'Java',
      'Spring Boot',
      'Python',
      'Django',
      'Go',
      'Kafka',
      'GraphQL',
      'Microservices'
    ],
    lpa: 12,
    teams: ['Platform', 'Core Services', 'Payments', 'Growth'],
    duties: [
      'Design, build and maintain scalable services using {a} and {b}',
      'Own the reliability of the APIs your team ships: monitoring, alerting and on-call rotation',
      'Model data and tune queries in {c}; review schema changes with the team',
      'Write clear technical designs and review pull requests thoughtfully',
      'Work with product and frontend engineers to turn requirements into well-scoped increments'
    ]
  },
  {
    key: 'frontend',
    titles: ['Frontend Developer', 'UI Engineer', 'React Developer', 'Web Developer', 'Frontend Engineer'],
    skills: [
      'React',
      'TypeScript',
      'JavaScript',
      'CSS',
      'HTML',
      'Next.js',
      'Redux',
      'Tailwind CSS',
      'Jest',
      'Webpack',
      'Accessibility',
      'Vue.js',
      'Storybook'
    ],
    lpa: 10,
    teams: ['Web', 'Design Systems', 'Growth', 'Consumer Apps'],
    duties: [
      'Build fast, accessible interfaces with {a} and {b}',
      'Turn designs into reusable components and contribute to our design system',
      'Improve performance and Core Web Vitals across the product',
      'Write unit and integration tests with {c}',
      'Collaborate closely with designers and backend engineers on API contracts'
    ]
  },
  {
    key: 'mobile',
    titles: ['Mobile Engineer', 'Android Developer', 'iOS Developer', 'React Native Developer', 'Flutter Developer'],
    skills: ['React Native', 'Flutter', 'Kotlin', 'Swift', 'Android', 'iOS', 'Firebase', 'Dart', 'Jetpack Compose', 'SwiftUI', 'REST APIs'],
    lpa: 12,
    teams: ['Mobile', 'Consumer Apps', 'Payments'],
    duties: [
      'Ship features in our mobile apps using {a} and {b}',
      'Keep crash-free rates and startup times healthy across a wide range of devices',
      'Integrate with backend APIs and handle offline and flaky-network states gracefully',
      'Work with {c} for analytics, push notifications and release tooling'
    ]
  },
  {
    key: 'data',
    titles: ['Data Analyst', 'Data Engineer', 'Data Scientist', 'Machine Learning Engineer', 'BI Developer', 'Analytics Engineer'],
    skills: [
      'Python',
      'SQL',
      'Pandas',
      'Power BI',
      'Tableau',
      'Spark',
      'Airflow',
      'Machine Learning',
      'TensorFlow',
      'Statistics',
      'ETL',
      'dbt',
      'Snowflake'
    ],
    lpa: 11,
    teams: ['Data Platform', 'Analytics', 'Machine Learning', 'Insights'],
    duties: [
      'Build and maintain reliable data pipelines using {a} and {b}',
      'Turn business questions into analyses, dashboards and experiments',
      'Own data quality: tests, documentation and lineage for the tables you publish',
      'Use {c} to model, evaluate and explain results to non-technical stakeholders'
    ]
  },
  {
    key: 'devops',
    titles: ['DevOps Engineer', 'Site Reliability Engineer', 'Cloud Engineer', 'Infrastructure Engineer', 'Platform Engineer'],
    skills: [
      'Docker',
      'Kubernetes',
      'AWS',
      'Terraform',
      'CI/CD',
      'Linux',
      'Jenkins',
      'Prometheus',
      'Ansible',
      'Azure',
      'GCP',
      'Grafana',
      'Bash'
    ],
    lpa: 14,
    teams: ['Infrastructure', 'Reliability', 'Developer Experience'],
    duties: [
      'Run and improve our cloud infrastructure on {a} using {b}',
      'Automate builds, tests and deployments so teams can ship safely many times a day',
      'Define SLOs, build observability with {c} and lead blameless incident reviews',
      'Harden security and manage cost across environments'
    ]
  },
  {
    key: 'qa',
    titles: ['QA Engineer', 'Test Automation Engineer', 'SDET', 'Quality Analyst'],
    skills: [
      'Selenium',
      'Playwright',
      'Cypress',
      'JIRA',
      'Test Automation',
      'Postman',
      'API Testing',
      'Java',
      'JavaScript',
      'Performance Testing',
      'JMeter'
    ],
    lpa: 8,
    teams: ['Quality', 'Platform', 'Consumer Apps'],
    duties: [
      'Design and maintain automated test suites with {a} and {b}',
      'Test APIs and user journeys; report defects with clear, reproducible steps',
      'Integrate tests into CI and keep flaky tests under control',
      'Partner with engineers on testability, using {c} for exploratory and regression testing'
    ]
  },
  {
    key: 'design',
    titles: ['Product Designer', 'UX Designer', 'UI Designer', 'UX Researcher', 'Visual Designer'],
    skills: [
      'Figma',
      'UX Research',
      'Prototyping',
      'Design Systems',
      'Adobe XD',
      'Illustrator',
      'User Testing',
      'Wireframing',
      'Interaction Design'
    ],
    lpa: 9,
    teams: ['Design', 'Product', 'Brand'],
    duties: [
      'Own the design of features from research and flows through to polished {a} files',
      'Run usability tests and turn findings into improvements',
      'Contribute to our design system with {b} components and documentation',
      'Present your work to product, engineering and leadership; incorporate feedback well'
    ]
  },
  {
    key: 'product',
    titles: ['Product Manager', 'Associate Product Manager', 'Technical Program Manager', 'Business Analyst', 'Project Manager'],
    skills: [
      'Product Management',
      'Roadmapping',
      'Agile',
      'SQL',
      'Stakeholder Management',
      'Analytics',
      'JIRA',
      'User Stories',
      'A/B Testing',
      'Scrum'
    ],
    lpa: 15,
    teams: ['Product', 'Growth', 'Operations'],
    duties: [
      'Define problems worth solving, write clear specs and prioritise with {a}',
      'Work with engineering and design to ship in small, measurable increments',
      'Track outcomes with {b} and decide what to build, improve or retire',
      'Keep stakeholders aligned through regular, honest communication using {c}'
    ]
  },
  {
    key: 'marketing',
    titles: [
      'Digital Marketing Executive',
      'Content Strategist',
      'SEO Specialist',
      'Growth Marketer',
      'Sales Executive',
      'Account Manager'
    ],
    skills: [
      'SEO',
      'Content Marketing',
      'Google Analytics',
      'Salesforce',
      'CRM',
      'Lead Generation',
      'Social Media',
      'Copywriting',
      'Email Marketing',
      'Google Ads',
      'HubSpot'
    ],
    lpa: 6,
    teams: ['Marketing', 'Sales', 'Growth', 'Brand'],
    duties: [
      'Plan and run campaigns across search, social and email using {a} and {b}',
      'Create content that explains our product clearly and earns attention',
      'Report on funnel performance in {c} and recommend what to double down on',
      'Coordinate with sales and product on launches and customer feedback'
    ]
  },
  {
    key: 'business',
    titles: [
      'HR Executive',
      'Talent Acquisition Specialist',
      'Accountant',
      'Finance Analyst',
      'Operations Executive',
      'Customer Support Lead'
    ],
    skills: [
      'Recruitment',
      'Talent Acquisition',
      'Payroll',
      'Excel',
      'Tally',
      'Financial Reporting',
      'GST',
      'Customer Support',
      'Zendesk',
      'Communication',
      'Vendor Management'
    ],
    lpa: 5,
    teams: ['People', 'Finance', 'Operations', 'Customer Success'],
    duties: [
      'Run day-to-day {a} processes accurately and on time',
      'Maintain records and reports in {b}; flag anomalies early',
      'Be a friendly, reliable point of contact for teammates and customers',
      'Improve our processes and documentation using {c}'
    ]
  }
];

export const CITIES = [
  'Chennai',
  'Bengaluru',
  'Hyderabad',
  'Pune',
  'Mumbai',
  'Delhi',
  'Gurugram',
  'Noida',
  'Kolkata',
  'Ahmedabad',
  'Kochi',
  'Coimbatore',
  'Jaipur',
  'Indore',
  'Remote'
];
/** Cities weighted towards the big hubs. */
export const CITY_WEIGHTS = [16, 18, 12, 11, 9, 7, 6, 5, 3, 3, 3, 2, 2, 1, 2];

export const FIRST_NAMES = [
  'Aarav',
  'Aditi',
  'Aditya',
  'Ananya',
  'Arjun',
  'Bhavya',
  'Chirag',
  'Deepa',
  'Dev',
  'Divya',
  'Farhan',
  'Gauri',
  'Harish',
  'Ishaan',
  'Isha',
  'Jaya',
  'Karan',
  'Kavya',
  'Kiran',
  'Lakshmi',
  'Mahesh',
  'Meera',
  'Mohan',
  'Nandini',
  'Naveen',
  'Neha',
  'Nikhil',
  'Nisha',
  'Omkar',
  'Pooja',
  'Pranav',
  'Priya',
  'Rahul',
  'Rajesh',
  'Rekha',
  'Rohan',
  'Sahana',
  'Sanjay',
  'Saanvi',
  'Shreya',
  'Siddharth',
  'Sneha',
  'Suresh',
  'Tanvi',
  'Uday',
  'Varun',
  'Vikram',
  'Vidya',
  'Yash',
  'Zoya',
  'Alice',
  'Ben',
  'Chloe',
  'Daniel',
  'Emma',
  'Farah',
  'George',
  'Hannah',
  'Ivan',
  'Julia',
  'Kenji',
  'Layla',
  'Marco',
  'Nora',
  'Omar',
  'Priyanka',
  'Quinn',
  'Rosa',
  'Samir',
  'Tara'
];
export const LAST_NAMES = [
  'Sharma',
  'Iyer',
  'Nair',
  'Reddy',
  'Patel',
  'Gupta',
  'Singh',
  'Kumar',
  'Menon',
  'Rao',
  'Joshi',
  'Mehta',
  'Das',
  'Banerjee',
  'Chatterjee',
  'Pillai',
  'Krishnan',
  'Subramanian',
  'Naidu',
  'Kapoor',
  'Malhotra',
  'Bose',
  'Kulkarni',
  'Deshmukh',
  'Shetty',
  'Hegde',
  'Bhat',
  'Varma',
  'Agarwal',
  'Jain',
  'Saxena',
  'Trivedi',
  'Ghosh',
  'Sen',
  'Mukherjee',
  'Thomas',
  'George',
  'Mathew',
  'Fernandes',
  "D'Souza",
  'Khan',
  'Ahmed',
  'Ali',
  'Sheikh',
  'Ansari',
  'Chopra',
  'Bhatia',
  'Sinha',
  'Mishra',
  'Pandey',
  'Tiwari',
  'Yadav',
  'Verma',
  'Lal',
  'Ramesh',
  'Prakash',
  'Anand',
  'Balan',
  'Chandran',
  'Gopal',
  'Smith',
  'Brown',
  'Tanaka',
  'Rossi',
  'Novak',
  'Haddad'
];

export const COMPANY_PREFIXES = [
  'Aster',
  'Argon',
  'Apex',
  'Basil',
  'Beacon',
  'Bluepeak',
  'Cedar',
  'Cobalt',
  'Comet',
  'Delta',
  'Ember',
  'Fable',
  'Granite',
  'Harbor',
  'Helix',
  'Indigo',
  'Ironclad',
  'Juniper',
  'Kestrel',
  'Krypton',
  'Lattice',
  'Lumina',
  'Meridian',
  'Mosaic',
  'Nimbus',
  'Nova',
  'Onyx',
  'Orbit',
  'Pixel',
  'Prism',
  'Quanta',
  'Quartz',
  'Ridge',
  'Sable',
  'Solstice',
  'Tandem',
  'Tidal',
  'Umbra',
  'Unity',
  'Vantage',
  'Vector',
  'Vertex',
  'Willow',
  'Wren',
  'Xenon',
  'Yonder',
  'Zenith',
  'Zephyr',
  'Zinc',
  'Ashwood'
];
export const COMPANY_SUFFIXES = [
  'Labs',
  'Systems',
  'Technologies',
  'Software',
  'Digital',
  'Analytics',
  'Cloud',
  'Works',
  'Solutions',
  'Networks',
  'Robotics',
  'Health',
  'Finance',
  'Logistics',
  'Media',
  'Commerce',
  'Studios',
  'Group',
  'Ventures',
  'Dynamics'
];
export const INDUSTRIES = [
  'Software',
  'FinTech',
  'HealthTech',
  'E-commerce',
  'EdTech',
  'Logistics',
  'Media',
  'Manufacturing',
  'Consulting',
  'Travel',
  'Telecom',
  'Energy'
];

export const INSTITUTIONS = [
  'Anna University',
  'VIT Vellore',
  'NIT Trichy',
  'BITS Pilani',
  'IIT Madras',
  'IIT Bombay',
  'PSG College of Technology',
  'SRM Institute',
  'Manipal Institute of Technology',
  'Delhi University',
  'Pune University',
  'JNTU Hyderabad',
  'RVCE Bengaluru',
  'Christ University',
  'Loyola College',
  'Symbiosis Pune',
  'Amity University',
  'Jadavpur University',
  'Osmania University',
  'Cochin University'
];
export const DEGREES: Array<[string, string]> = [
  ['B.Tech', 'Computer Science'],
  ['B.Tech', 'Information Technology'],
  ['B.E.', 'Electronics'],
  ['BCA', 'Computer Applications'],
  ['B.Sc', 'Statistics'],
  ['B.Com', 'Accounting'],
  ['BBA', 'Business Administration'],
  ['M.Tech', 'Software Engineering'],
  ['MCA', 'Computer Applications'],
  ['MBA', 'Marketing'],
  ['B.Des', 'Design'],
  ['B.A.', 'English']
];

export const EMPLOYER_NAMES = [
  'Infoworks',
  'CodeHarbor',
  'Bytecraft',
  'Tessellate',
  'Paperplane',
  'Greenfield Tech',
  'Crestline',
  'Openbook',
  'Sunrise Digital',
  'Riverbend Systems',
  'Blueshift',
  'Pinecone Labs',
  'Copperleaf',
  'Skybridge',
  'Nightowl Software',
  'Datastream',
  'Kite Analytics',
  'Stackwise',
  'Cloudnine Tech',
  'Mapleton'
];

export const BENEFITS = [
  'Health insurance for you and your family',
  'Flexible working hours and a hybrid or remote-friendly setup',
  'Annual learning budget for courses and conferences',
  'Paid time off, plus a company-wide year-end break',
  'Home-office setup allowance',
  'Performance bonus and stock options for full-time roles',
  'Mentorship from experienced engineers and managers',
  'A small, friendly team that values clear writing and honest feedback'
];

export const NOTE_TEXTS = [
  'Strong fundamentals; discussed system design in depth. Worth moving forward.',
  'Good communication. Needs a deeper technical screen on data modelling.',
  'Portfolio is impressive, especially the accessibility work.',
  'Available to join in 30 days. Salary expectation is within range.',
  'Resume matches the required skills well. Schedule with the hiring manager.',
  'Great culture fit in the call; slightly light on hands-on experience with the stack.',
  'Referred by an existing employee. Prioritise.',
  'Notice period is 60 days; asked if it can be shortened.',
  'Solid take-home submission. Clean code and good tests.',
  'Not a fit for this opening, but keep in mind for a future senior role.'
];
